SkV getKey fix for returned records
futurewei-cloud/chogori-platform pull request #100
Opened 2021-01-11 01:33 UTC by jfunston

Also cleanup and tighten SKV interface

2021-01-11 18:12 UTC, jerryhfeng submitted a review, later dismissed
Looks good to me.

Conditional approval regarding one of comments, assuming it is correct the have the havingKey/KeyContructed bool set in constructor is correct.

2021-01-11 18:35 UTC, iafuture requested changes

2021-01-11 18:35 UTC, iafuture commented on src/k2/dto/SKVRecord.cpp
> +    for (size_t i = 0; i < partitionKeys.size() + rangeKeys.size(); ++i) {
Are we preventing the same field from being used in both partition and range key? i.e. is it possible for pk.size() + rk.size() to be < allFields.size()

2021-01-11 18:35 UTC, iafuture commented on src/k2/dto/SKVRecord.cpp
> +        DO_ON_NEXT_RECORD_FIELD(*this, makeKeyString, i);
why pass this int if it isn't used by the func?

2021-01-12 00:50 UTC, iafuture approved these changes

2021-01-12 00:51 UTC, merged