implement tpcc Delivery Transaction
futurewei-cloud/chogori-platform pull request #102
Opened 2021-01-14 06:18 UTC by YazhiFeng

2021-01-14 23:11 UTC, jfunston requested changes
Looks good! Only a few comments to address.

2021-01-14 23:11 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +                        _NO_O_ID[idx] = *orderIDOpt;
Maybe an assert before this line that orderIDOpt is not null

2021-01-14 23:11 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +            return do_with(std::move(response.query), [this, idx] (Query& query_cid) {
This is a query instead of a read because you want to do projection? If so can you add a comment explaining that?

2021-01-14 23:11 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +                query_cid.endScanRecord.serializeNext<int64_t>(_NO_O_ID[idx] + 1);
I recently fixed a bug in the query, now if it startScanRecord == endScanRecord the record will be returned, so you can remove the +1 here to be more clear.

2021-01-14 23:11 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +                query_oid.setLimit(1);
It would be more efficient if we could do the whole batch size in one query. Up to you if you want to change it for this PR or not.

2021-01-14 23:11 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +                return do_with(std::move(response.query), [this, idx, lineNum] (Query& query_order_line) {
Can this be one query for all of the LineNumbers?

2021-02-02 21:06 UTC, jfunston requested changes
One new comment to address and you will also need to rebase onto the current master. The main change you will need to deal with is the macros for logging have changed.

2021-02-02 21:06 UTC, jfunston commented on src/k2/cmd/tpcc/transactions.h
> +                return _txn.query(query_order_line)
You need to call query until "isDone" is true so that you handle paginated responses.

2021-02-03 10:26 UTC, YazhiFeng commented
All comments have been resolved. 
But I got one problem building chogori-platform based on the newest version and perhaps it is related to the fmt.

If the fmt is install using the 6.1.2 version as in chogori-seastar-rd script, the following compilation error is reported:
`
In function ‘const char* k2::printTime(const TimePoint&)’:
error: call of overloaded ‘format_to_n(char [24], long unsigned int, const char [3], k2::Timestamp_ts&)’ is ambiguous
  111 |     fmt::format_to_n(buffer, sizeof(buffer), "{}", ts);
/usr/local/include/fmt/format.h:3369:37: note: candidate: ‘fmt::v6::format_to_n_result<OutputIt> fmt::v6::format_to_n(OutputIt, std::size_t, const S&, const Args& ...) [with OutputIt = char*; S = char [3]; Args = {k2::Timestamp_ts}; typename std::enable_if<(fmt::v6::internal::is_string<S>::value && fmt::v6::internal::is_output_iterator<It>::value), int>::type <anonymous> = 0; std::size_t = long unsigned int]’
 3369 | inline format_to_n_result<OutputIt> format_to_n(OutputIt out, std::size_t n,
...
`

if using the newest version of the fmt on git (https://github.com/fmtlib/fmt), the following compilation error is reported:
`
//usrusr//binbin//ldld::  //usrusr//locallocal//libinclude//libseastar.afmt(/reactor.cc.oformat.h)::862 :in  undefinedfunction  reference` voidto  fmt`:fmt::v6::v6::internal::internal::nonfinite_writer:<basic_datachar<>void:>::operator:(digits)'<
char/*usr>/(binchar/*ld&:& )/ usrconst/'local:/
lib//usrlibseastar.a/(localreactor.cc.o/)include:/ fmtin/ format.hfunction: 1370`:char *undefined  fmtreference: :tov6 :`:fmtinternal::::v6format_decimal:<:unsignedinternal :__int128:,basic_data <charvoid,> :fmt::signs:'v6
:/:usrinternal/:bin:/format_decimalld<:char ,/ usrchar/*local,/ includeunsigned/ fmt__int128/>format.h(:char1370*:,  undefinedunsigned  reference__int128 ,to  int`)fmt::::{v6lambda:(:charinternal*:):#basic_data1<}void>>(:fmt::signs:'v6
:/:usrinternal/:bin:/format_decimalld<:char ,/ usrchar/*local,/ libunsign^Cmake[2]: *** wait: No child processes.  Stop.
...
`

Hope to get your help!

2021-02-03 19:36 UTC, iafuture commented
Hi Yazhi,
Can you please try with our fmt fork instead:
https://github.com/futurewei-cloud/chogori-fmt

2021-02-03 21:23 UTC, iafuture commented
I've fixed the install_deps scripts for both seastar-rd and platform. Please do a fresh build for both

2021-02-04 03:26 UTC, jfunston approved these changes
Looks good, thanks!

2021-02-04 03:26 UTC, merged