Idempotent write ops and DataRecord refactor
futurewei-cloud/chogori-platform pull request #152
Opened 2021-03-11 23:23 UTC by jfunston

Makes write ops idempotent, which fixes failures on rejectIfExist=true retries. Also refactors DataRecord to split committed records from write intents, and removes unnecessary data from committed records. Closes #116

2021-03-15 17:14 UTC, iafuture requested changes

2021-03-15 17:48 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +    if (versions.WI->txnId.mtr.timestamp.compareCertain(timestamp) == 0) {
need tsoid

2021-03-16 20:03 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> -                            K2EXPECT(log::k23si, status, dto::K23SIStatus::KeyNotFound);
Added back in the ability to remove a key from the indexer and added this check back in.

2021-03-16 20:03 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> -                        K2EXPECT(log::k23si, val1.records[0].txnId.mtr.txnid, mtr.txnid);
Added back in some of the checks that I could

2021-03-16 20:04 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> -                return doFinalize(k8, k8, mtr, collname, true, ErrorCaseOpt::NoInjection)
Changed this test to use an invalid MTR instead of an invalid TRH key.

2021-03-16 20:04 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +    if (versions.WI->txnId.mtr.timestamp.compareCertain(timestamp) == 0) {
Checked the code and compareCertain does use the tsoID

2021-03-16 20:05 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +        bool needPush = !record ? _needPush(versions, request.mtr.timestamp) : false;
getDataRecord was only used for read path so renamed it to make it more clear. Fixed this bug by making it return a nullptr if there is a WI from a different txn and earlier timestamp.

2021-03-17 18:38 UTC, iafuture requested changes

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
> +    if (versions.WI.has_value() && versions.WI->txnId.mtr != request.mtr) {
I think this should only be done for IPR WI. If the WI is aborted, we should probably remove it from memory

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
> +    if (versions.WI.has_value() && request.mtr == versions.WI->txnId.mtr &&
same as above - i think this only applies for IPR WI

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
>      // If the second oldest is newer than we are, then we won't commit even if we win a PUSH against the WI.
Should we consider the op ID now for stale write? I.e. lower sequence# should be considered stale against a higher one

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
> +            K2LOG_D(log::skvsvr, "Partition: {}, cannot abort committed record", _partition);
We should extend the message in the response to explain why we can't finalize

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
> +    if (request.action == dto::EndAction::Abort) {
I think this block would read better if you used a switch instead of another if-elseif layer

2021-03-17 18:38 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
> +        return RPCResponse(dto::K23SIStatus::OperationNotAllowed("cannot finalize txn"), dto::K23SITxnFinalizeResponse());
a bit better message here - why can't we finalize?

2021-03-17 19:19 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +K23SIPartitionModule::_getDataRecordForRead(VersionSet& versions, dto::Timestamp& timestamp) {
read with timestamp lower than any committed record

2021-03-17 22:17 UTC, iafuture requested changes

2021-03-17 22:17 UTC, iafuture commented on src/k2/module/k23si/Module.cpp
>              if (record.timestamp.compareCertain(txnId.mtr.timestamp) == 0) {
I think it'd be slightly more efficient(fewer branches) to compare once and break, something like
``` c++
int comp = record.timetamp.compareCertain(txnId.mtr.timestamp);
found = !comp;
if (comp <= 0) break;
```

2021-03-17 23:04 UTC, iafuture approved these changes

2021-03-17 23:05 UTC, merged