Drop collection
futurewei-cloud/chogori-platform pull request #160
Opened 2021-04-05 21:24 UTC by jfunston

Closes #138

2021-04-06 16:55 UTC, iafuture requested changes

2021-04-06 16:55 UTC, iafuture commented on docs/RFC/drop_collection.md
> +The CPO is the authoratative truth of collection metadata such as the partition map, version, and the
you should let MD format the paragraphs instead of manual \n's

2021-04-06 16:55 UTC, iafuture commented on src/k2/assignmentManager/AssignmentManager.cpp
> +        _pmodule = nullptr;
can you add Info logs before/after this call?

2021-04-06 16:55 UTC, iafuture commented on src/k2/cpo/service/CPOService.cpp
> +seastar::future<> CPOService::_offloadCollection(dto::Collection& collection) {
you don't have any retries here(which is fine) but we should make sure we can retry from the outside if things time out/fail.

I think to achieve that we need:
- 404_not_found response from node if the collection has already been offloaded there
- handling of 404 here as a non-error condition (along with the 200 ok)
- we should return any other error status out and only clean up the cpo state if everything succeeded
- we should be able to mark the cpo state as "deleted" when we receive a drop request. That way we can still have the metadata around but we know not to return it to clients. The metadata should be here until all partitions ACK the drop. If any fail, we leave it untouched and let the client retry if they want

2021-04-07 17:56 UTC, iafuture approved these changes

2021-04-07 18:13 UTC, iafuture approved these changes

2021-04-07 18:44 UTC, jerryhfeng approved these changes

2021-04-07 18:44 UTC, jerryhfeng commented on src/k2/cpo/service/CPOService.cpp
> +
check deleted flag here for re-try drop request?

2021-04-07 18:44 UTC, jerryhfeng commented on src/k2/cmd/nodepool/nodepool_main.cpp
> -    app.addApplet<k2::PartitionManager>();
Why removing this? Leave us no possibility to host multiple partition (of same collection) in one node in the future?

2021-04-07 18:44 UTC, jerryhfeng commented on src/k2/partitionManager/PartitionManager.h
> -class PartitionManager {
Same concern about possible support of multiple partitions in the future on one node.

2021-04-09 16:59 UTC, merged