3SI Transaction test cases scenario 02 #38
futurewei-cloud/chogori-platform pull request #39
Opened 2020-09-10 14:02 UTC by YazhiFeng

code functionality tested correct. 
But leave two question as listed on https://github.com/futurewei-cloud/chogori-platform/issues/38. 
The code is submitted in case you need to check the code.

2020-09-11 07:57 UTC, YazhiFeng commented
All scenario-02 cases are implemented and the "failed_assignment" bug is fixed. Please check the PR.

2020-09-11 23:30 UTC, jfunston requested changes
You will also need to rebase on master since we merged the SKV interface which changes the READ and WRITE dtos. I made the changes to your previous test cases, you can refer to them to see how to update the code.

2020-09-11 23:30 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> +                        K2EXPECT(status, Statuses::S404_Not_Found);
Here and elsewhere you can use the statuses from K23SIStatus in dto/K23SI.h which is a bit more clear in intent

2020-09-11 23:30 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> +    // SC02 case11 & 12 & 13 & 14: Async END test (end-but-not-finalized key )
Can you explain a bit more in the comment what the purpose of this test case is?

2020-09-11 23:30 UTC, jfunston commented on test/k23si/3SITxnTest.cpp
> +                        K2EXPECT(status2, Statuses::S405_Method_Not_Allowed);
What do we get 405 here? I would think it should succeed. Am I misunderstanding it?

2020-09-16 01:27 UTC, jfunston commented
Looks good, once you get it rebased on latest master with the new SKV interface it will be good to merge.

2020-09-16 17:59 UTC, jfunston approved these changes

2020-09-16 18:00 UTC, merged