Implement projection for Query
futurewei-cloud/chogori-platform pull request #72
Opened 2020-10-23 10:36 UTC by YazhiFeng

Projection has been implemented and a test case is added.

2020-10-23 21:00 UTC, jfunston requested changes

2020-10-23 21:00 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +                    response.results.push_back(storage.share());
You can use std::move(storage) instead of share()

2020-10-23 21:00 UTC, jfunston commented on src/k2/module/k23si/Module.cpp
> +    projectionRec.excludedFields = excludedFields;
You can use std::move here too

2020-10-23 21:00 UTC, jfunston commented on test/k23si/QueryTest.cpp
> +                          std::vector<k2::String> projection=std::vector<k2::String>()) {
I think you should change this function so it returns the result set to the caller, then the tests for projection can test that the correct data is returned. The already existing tests can just ignore the result.

2020-10-23 21:00 UTC, jfunston commented on test/k23si/QueryTest.cpp
> +    return doQuery("a", "c", -1, false, 2, 1, k2::dto::K23SIStatus::OK, {"partition"});
Like I mentioned above, let's check that the data is correct. Also, can you add a test that tries to project a field that is not part of the schema?

2020-10-26 09:34 UTC, YazhiFeng commented
Use std::move to return value, func doQuery() returns val_set, and add a testcase.

2020-10-26 22:05 UTC, jfunston approved these changes
Looks good, thanks. You can start on https://github.com/futurewei-cloud/chogori-platform/issues/59 next. As always feel free to ask me questions on the issue or in the open source meeting.

2020-10-26 22:06 UTC, merged

2020-10-27 18:51 UTC, jerryhfeng commented on src/k2/module/k23si/Module.cpp
> +    Payload payload(Payload::DefaultAllocator);                     // payload for projection
Minor: Could you rename it to projectedPayload for better readability.